Add isInteger32
char0n/ramda-adjunct pull request #1826
Opened 2021-03-28 11:52 UTC by skShekhar

This PR adds a predicate to determine if an integer is 32 bits. #1282

2021-03-29 07:32 UTC, skShekhar commented
@char0n Can you review this PR

2021-03-29 08:02 UTC, char0n commented
Thanks for contributing. I'll get to core review ASAP.

2021-03-31 12:12 UTC, char0n requested changes
Great start! Please take a look at my code review comments. We're still missing two major things: typescript typings and tests for them. See for example this PR for more information about how to create ones: https://github.com/char0n/ramda-adjunct/commit/e9d321aef8bf1200d9b5e3bccd59f787eb8f31f5

2021-03-31 12:12 UTC, char0n commented on src/isInteger32.js
> + * Checks whether the passed value is a 32 bit integer.
```suggestion
 * Checks whether the passed value is a signed 32 bit integer.
```

2021-03-31 12:12 UTC, char0n commented on src/isInteger32.js
> + * @memberOf RA
```suggestion
 * @aliases isInt32
 * @memberOf RA
```

2021-03-31 12:12 UTC, char0n commented on src/isInteger32.js
> + * @see {@link RA.isInteger32|isInteger32}
```suggestion
 * @see {@link RA.toInteger32|toInteger32}
```

2021-03-31 12:12 UTC, char0n commented on src/isInteger32.js
> +const _isInteger32 = curryN(1, (val) => toInteger32(val) === val);
```suggestion
const isInteger32 = curryN(1, (val) => toInteger32(val) === val);
```

2021-03-31 12:12 UTC, char0n commented on src/isInteger32.js
> +export default _isInteger32;
```suggestion
export default isInteger32;
```

2021-03-31 12:12 UTC, char0n commented on test/isInteger32.js
> +  });
```suggestion
  });
  
  it('should support placeholder to specify "gaps"', function () {
    const isInteger32 = RA.isInteger32(R.__);

    assert.isTrue(isInteger32(0));
  });
```

2021-04-02 10:27 UTC, skShekhar commented
@char0n I've added missing typescript typing and tests for `isInteger32`. The review comments have also been addressed

2021-04-02 17:52 UTC, char0n commented on src/isInteger32.js
> + * @see {@link RA.isInteger32|isInteger32}
Just for reference: you can directly commit my suggestion by clicking on "Commit suggestion" button. More info here: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request

2021-04-02 17:53 UTC, char0n approved these changes
Looks great! Your work is going to be part of next RA release.

2021-04-02 18:16 UTC, merged